<?php
if(!defined('THINK_PATH')) exit();
return $array = array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'www.51kuaiwei.com',
  'DB_USER' => 'root',
  'DB_PWD' => 'XZjORnuQRXzOaGoA',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'wxq_',
  'DB_BACKUP' => '../Data/backup',
  'RBAC_ROLE_TABLE' => 'wxq_role',
  'RBAC_USER_TABLE' => 'wxq_user',
  'RBAC_ACCESS_TABLE' => 'wxq_access',
  'RBAC_NODE_TABLE' => 'wxq_node',
  'URL_CASE_INSENSITIVE' => true,
  'URL_MODEL' => 1,
  'DEFAULT_THEME' => 'weixinqun',
  'WX_TOKEN' => 'yf5aa41bd76637e860619011',
  'SITE_NAME' => '51快微网',
  'SITE_TITLE' => '51快微网 | 微信群_微商代理_微商货源_微信公众号二维码导航',
  'SITE_KEYWORDS' => '微信群,微商代理,微商货源,51快微网',
  'SITE_DESCRIPTION' => '51快微网(快微网)是汇集全国各地各行业微信群二维码、微信公众号二维码、微商品牌代理二维码导航网站,收录海量微商货源,是您快速获得微商资源的最佳平台。',
  'RMB_CHANGE_INTERGRAL' => 20,
  'ISCOMMENT' => 1,
  'COMMENTTYPE' => 1,
  'ISADDACCOUNT' => 0,
  'XFINTERGRAL' => 10,
  'ISAUTOVERIFY' => 0,
  'YUFUMARK' => '',
  'ISTASK' => 0,
  'TASKURL' => '',
  'URL_PATHINFO_DEPR' => '/',
);
?>